[project]
name = "DiscordRichPresence"
authors = [{ name = "Breadn" }]
version = "1.1.1"
description = "Shows your current class, level, and map on your Discord profile while playing.\n\nUpdates every 15 seconds."

[tool.sdkmod]
name = "Discord Rich Presence"
mod_type = "Standard"
supported_games = ["BL1", "BL1E"]
coop_support = "ClientSide"
auto_enable = true
download = "https://github.com/Breadn11/BL1E_Mods/raw/refs/heads/main/DiscordRichPresence/packaged/DiscordRichPresence.sdkmod"